from app.crud.organization import organization
from app.crud.team import team
from app.crud.advisor import advisor
from app.crud.customer import customer
from app.crud.call import call
from app.crud.transcript import transcript
from app.crud.analysis import analysis
from app.crud.issue_tag import issue_tag
from app.crud.feedback import feedback